// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3ONu1LVSNAMKS7gLnNyAljRGnxY0FuEE',
    appId: '1:405217690918:web:fa29471ff2ab2e67076de7',
    messagingSenderId: '405217690918',
    projectId: 'iiit-crophealthcheck',
    authDomain: 'iiit-crophealthcheck.firebaseapp.com',
    storageBucket: 'iiit-crophealthcheck.appspot.com',
    measurementId: 'G-MB9N6HP0XT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ-dgBU54whmepZP1hhWT7_srOZoXI5uo',
    appId: '1:405217690918:android:8478ca3411101fe8076de7',
    messagingSenderId: '405217690918',
    projectId: 'iiit-crophealthcheck',
    storageBucket: 'iiit-crophealthcheck.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARgMeAzrZ_I9d3UbeWspjebfLRLol-K2I',
    appId: '1:405217690918:ios:27d95e5e893cad02076de7',
    messagingSenderId: '405217690918',
    projectId: 'iiit-crophealthcheck',
    storageBucket: 'iiit-crophealthcheck.appspot.com',
    iosClientId: '405217690918-5ko4ofclif4p0oguj577ptshrb51vh9v.apps.googleusercontent.com',
    iosBundleId: 'com.example.cropDiseaseDetection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARgMeAzrZ_I9d3UbeWspjebfLRLol-K2I',
    appId: '1:405217690918:ios:27d95e5e893cad02076de7',
    messagingSenderId: '405217690918',
    projectId: 'iiit-crophealthcheck',
    storageBucket: 'iiit-crophealthcheck.appspot.com',
    iosClientId: '405217690918-5ko4ofclif4p0oguj577ptshrb51vh9v.apps.googleusercontent.com',
    iosBundleId: 'com.example.cropDiseaseDetection',
  );
}
